Try fix fs-extra error (presumably caused by changed glob star semantics)
Chasing root cause for

   Error: Source and destination must not be the same.

Not reproducable, locally.
Irregularily happening on CI runs.